#!/usr/bin/env bash
# Configuring sub-domains

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
  subdomains=("www" "lb-01" "web-01" "web-02")
else
  subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
  result=$(dig "$sub.$domain" +short)
  record_type=$(dig "$sub.$domain" +short | awk '{ print $4 }')

  echo "The subdomain $sub is a $record_type record and points to $result"
done

