#!/bin/env bash
#configuring subdomain with https

domain=$1
subdomain=$2

function get_subdomain_info() {
  local subdomain=$1
  local record_type=$(dig $subdomain.$domain | awk '/^'$subdomain'\.'$domain'\./ {print $4}')
  local destination=$(dig $subdomain.$domain | awk '/^'$subdomain'\.'$domain'\./ {print $5}')
  
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ -z "$subdomain" ]; then
  get_subdomain_info "www"
  get_subdomain_info "lb-01"
  get_subdomain_info "web-01"
  get_subdomain_info "web-02"
else
  get_subdomain_info $subdomain
fi

