#!/usrbin/env bash
# Function to display subdomain information

display_subdomain_info() {
    local domain=$1
    local subdomain=$2
    local record_type=$(dig $subdomain.$domain | awk '/ANSWER SECTION/ {getline; print $4}')
    local destination=$(dig $subdomain.$domain | awk '/ANSWER SECTION/ {getline; print $5}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script
domain=$1
subdomain=$2

# Display information for specified subdomain or default subdomains
if [ -n "$subdomain" ]; then
    display_subdomain_info $domain $subdomain
else
    display_subdomain_info $domain www
    display_subdomain_info $domain lb-01
    display_subdomain_info $domain web-01
    display_subdomain_info $domain web-02
fi

