#!usr/bin/env bash
# Configure ssl certificate

# Install HAProxy
apt-get install -y haproxy

# Obtain SSL certificate using Certbot
certbot certonly --standalone -d www.example.com

# Configure HAProxy for SSL termination
cat > /etc/haproxy/haproxy.cfg <<EOF
frontend www-https
  bind *:443 ssl crt /etc/letsencrypt/live/www.example.com/fullchain.pem
  reqadd X-Forwarded-Proto:\ https
  default_backend backend-www

backend backend-www
  server web-server 127.0.0.1:80
EOF

# Restart HAProxy
service haproxy restart

