#!/usr/bin/env bash
# Transfer file from client to server

# Check if at least 4 parameters are provided
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
path_to_file=$1
ip=$2
username=$3
ssh_key=$4

# Transfer file using scp
scp -o StrictHostKeyChecking=no -i $ssh_key $path_to_file $username@$ip:~/

# Check if the transfer was successful
if [ $? -eq 0 ]; then
    echo "File transfer successful!"
else
    echo "File transfer failed."
fi

