#!/usr/bin/env bash
# install nginx-web_server

# Update apt package index
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Configure nginx
sudo echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Reload nginx configuration
sudo nginx -s reload

