#!/usr/bin/env bash
#

# Update the package list and install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create a default Nginx configuration file that returns "Hello World!"
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
    server_name _;
    location / {
        return 200 'Hello World!';
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
sudo /etc/init.d/nginx restart
