#!/usr/bin/env bash
# install nginx web_server

# Update apt package index and upgrade existing packages
sudo apt update
sudo apt upgrade -y

# Install nginx web server
sudo apt install nginx -y

# Configure nginx to listen on port 80
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Configure nginx to return "Hello World!" at root
sudo bash -c 'echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        add_header X-Hello-World "Hello World!";
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default'

# Restart nginx to apply changes
sudo service nginx restart

