#!/usr/bin/env bash
# custom http response


# Update packages
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Add custom HTTP header to Nginx configuration
sudo sed -i '/server {/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Test Nginx configuration
sudo nginx -t

# Reload Nginx service
sudo systemctl reload nginx

