#!/usr/bin/env bash
# Install and configure HAProxy load balancer

sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 54.236.25.34:80 check
    server web-02 54.174.243.119:80 check
EOT

# Enable HAProxy as a service
sudo systemctl enable haproxy

# Start HAProxy service
sudo systemctl start haproxy

