#!/usr/bin/env bash
# Install load balancer

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 171919-web-01:80 check
    server web-02 171919-web-02:80 check
EOF

# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart

