#!/usr/bin/env bash
# Update package list and install HAproxy

sudo apt-get update
sudo apt-get install -y haproxy

# Enable HAproxy service to be managed via init script
sudo systemctl enable haproxy

# Configure HAproxy to send traffic to web-01 and web-02 with round-robin algorithm
cat << EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 STUDENT_ID-web-01:80 check
    server web-02 STUDENT_ID-web-02:80 check
EOF

# Reload HAproxy service to apply changes
sudo systemctl reload haproxy

