#!/usr/bin/env bash
# Display the time for 12 hours and 59 minutes

hour=0
minute=1

while [ $hour -lt 13 ]
do
  printf "%02d:%02d\n" $hour $minute
  
  minute=$((minute+1))
  
  if [ $minute -eq 60 ]
  then
    minute=1
    hour=$((hour+1))
  fi
done

