#!/usr/bin/env bash
# Firewall configuration to block all incoming traffics except TCP ports 22(SSH), 443(HTTPS SSL) and 80(HTTP)

# Install ufw
sudo apt-get update
sudo apt-get install ufw -y

# Set default incoming policy to deny
sudo ufw default deny incoming

# Allow incoming SSH, HTTPS, and HTTP traffic
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

# Enable the firewall
sudo ufw enable

# Display firewall status
sudo ufw status

