#!/usr/bin/env bash
# Fixing the web server to return Hello Holberton

docker run -p 8080:80 -d -it holbertonschool/265-0
docker exec -it $(container_id) /bin/bash
cd /etc/apache2/sites-available
DirectoryIndex index.html
service apache2 restart
exit
curl 0:8080

