#!/usr/bin/env bash
# Fixing the web server to return Hello Holberton

# Start the Docker container
docker run -p 8080:80 -d -it holbertonschool/265-0

# Get the container ID
container_id=$(docker ps -lq)

# Execute commands inside the container
docker exec -it "$container_id" /bin/bash -c '
  cd /var/www/html || exit
  echo "apache2 is running" >> index.html
  service apache2 restart
'

# Test the web server
curl http://localhost:8080

